language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script:
        - yarn test --ci --coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
