version: 2.1
orbs:
  react: thefrontside/react@0.2.0
  codecov: codecov/codecov@1.1.3
jobs:
  upload-coverage:
    docker:
      - image: circleci/node:10
    working_directory: ~/artifacts
    steps:
      - codecov/upload:
          file: ./coverage
workflows:
  client:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
      - upload-coverage:
          requires:
            - react/coverage
