version: 2.1
orbs:
  react: thefrontside/react@0.2.0
  codecov: codecov/codecov@1.1.3
jobs:
  upload-coverage:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test --ci --coverage
      - codecov/upload:
          file: ./coverage
  arbitrary:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: ls
      - run: pwd
workflows:
  client:
    jobs:
      - arbitrary